/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "dff_async.v:1.1-13.10" *)
module dff_async(clk, d, rst, q);
  (* src = "dff_async.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "dff_async.v:3.16-3.17" *)
  input d;
  wire d;
  (* src = "dff_async.v:5.16-5.17" *)
  output q;
  reg q;
  (* src = "dff_async.v:4.16-4.19" *)
  input rst;
  wire rst;
  (* src = "dff_async.v:7.5-12.8" *)
  always @(posedge clk, posedge rst)
    if (rst) q <= 1'h0;
    else q <= d;
endmodule
