/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "dff_const2.v:1.1-10.10" *)
module dff_const2(clk, reset, q);
  (* src = "dff_const2.v:1.25-1.28" *)
  input clk;
  wire clk;
  (* src = "dff_const2.v:1.54-1.55" *)
  output q;
  wire q;
  (* src = "dff_const2.v:1.36-1.41" *)
  input reset;
  wire reset;
  assign q = 1'h1;
endmodule
