/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "dff_sync_async.v:1.1-18.10" *)
module dff_sync_async(clk, d, sync_rst, async_rst, q);
  (* src = "dff_sync_async.v:8.5-17.8" *)
  wire _0_;
  (* src = "dff_sync_async.v:8.5-17.8" *)
  wire _1_;
  (* src = "dff_sync_async.v:3.16-3.17" *)
  wire _2_;
  (* src = "dff_sync_async.v:4.16-4.24" *)
  wire _3_;
  (* src = "dff_sync_async.v:5.16-5.25" *)
  input async_rst;
  wire async_rst;
  (* src = "dff_sync_async.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "dff_sync_async.v:3.16-3.17" *)
  input d;
  wire d;
  (* src = "dff_sync_async.v:6.16-6.17" *)
  output q;
  reg q;
  (* src = "dff_sync_async.v:4.16-4.24" *)
  input sync_rst;
  wire sync_rst;
  sky130_fd_sc_hd__nor2b_1 _4_ (
    .A(_3_),
    .B_N(_2_),
    .Y(_1_)
  );
  (* src = "dff_sync_async.v:8.5-17.8" *)
  always @(posedge clk, posedge async_rst)
    if (async_rst) q <= 1'h0;
    else q <= _0_;
  assign _2_ = d;
  assign _3_ = sync_rst;
  assign _0_ = _1_;
endmodule
