/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "opt_check.v:2.1-4.10" *)
module opt_check(a, b, y);
  (* src = "opt_check.v:2.25-2.26" *)
  wire _0_;
  (* src = "opt_check.v:2.35-2.36" *)
  wire _1_;
  (* src = "opt_check.v:2.46-2.47" *)
  wire _2_;
  (* src = "opt_check.v:2.25-2.26" *)
  input a;
  wire a;
  (* src = "opt_check.v:2.35-2.36" *)
  input b;
  wire b;
  (* src = "opt_check.v:2.46-2.47" *)
  output y;
  wire y;
  sky130_fd_sc_hd__and2_0 _3_ (
    .A(_1_),
    .B(_0_),
    .X(_2_)
  );
  assign _1_ = b;
  assign _0_ = a;
  assign y = _2_;
endmodule
