/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "opt_check.v:10.1-12.10" *)
module opt_check3(a, b, c, y);
  wire _0_;
  (* src = "opt_check.v:10.26-10.27" *)
  wire _1_;
  (* src = "opt_check.v:10.36-10.37" *)
  wire _2_;
  (* src = "opt_check.v:10.45-10.46" *)
  wire _3_;
  (* src = "opt_check.v:10.56-10.57" *)
  wire _4_;
  (* src = "opt_check.v:10.26-10.27" *)
  input a;
  wire a;
  (* src = "opt_check.v:10.36-10.37" *)
  input b;
  wire b;
  (* src = "opt_check.v:10.45-10.46" *)
  input c;
  wire c;
  (* src = "opt_check.v:10.56-10.57" *)
  output y;
  wire y;
  sky130_fd_sc_hd__and3_1 _5_ (
    .A(_2_),
    .B(_3_),
    .C(_1_),
    .X(_4_)
  );
  assign _2_ = b;
  assign _3_ = c;
  assign _1_ = a;
  assign y = _4_;
endmodule
