/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "opt_check.v:6.1-8.10" *)
module opt_check2(a, b, y);
  (* src = "opt_check.v:6.26-6.27" *)
  wire _0_;
  (* src = "opt_check.v:6.36-6.37" *)
  wire _1_;
  (* src = "opt_check.v:6.47-6.48" *)
  wire _2_;
  (* src = "opt_check.v:6.26-6.27" *)
  input a;
  wire a;
  (* src = "opt_check.v:6.36-6.37" *)
  input b;
  wire b;
  (* src = "opt_check.v:6.47-6.48" *)
  output y;
  wire y;
  sky130_fd_sc_hd__or2_0 _3_ (
    .A(_0_),
    .B(_1_),
    .X(_2_)
  );
  assign _0_ = a;
  assign _1_ = b;
  assign y = _2_;
endmodule
