/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "dff_sync.v:1.1-16.10" *)
module dff_sync(clk, d, rst, set, q);
  wire _0_;
  wire _1_;
  (* src = "dff_sync.v:3.16-3.17" *)
  wire _2_;
  (* src = "dff_sync.v:5.16-5.19" *)
  wire _3_;
  (* src = "dff_sync.v:2.16-2.19" *)
  input clk;
  wire clk;
  (* src = "dff_sync.v:3.16-3.17" *)
  input d;
  wire d;
  (* src = "dff_sync.v:6.16-6.17" *)
  output q;
  reg q;
  (* src = "dff_sync.v:4.16-4.19" *)
  input rst;
  wire rst;
  (* src = "dff_sync.v:5.16-5.19" *)
  input set;
  wire set;
  sky130_fd_sc_hd__or2_0 _4_ (
    .A(_3_),
    .B(_2_),
    .X(_1_)
  );
  (* src = "dff_sync.v:8.5-15.8" *)
  always @(posedge clk)
    if (rst) q <= 1'h0;
    else q <= _0_;
  assign _3_ = set;
  assign _2_ = d;
  assign _0_ = _1_;
endmodule
