/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "demux_1to8_gen.v:2.1-12.10" *)
module demux_1to8_gen(out, sel, i);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  (* src = "demux_1to8_gen.v:2.72-2.73" *)
  wire _13_;
  (* src = "demux_1to8_gen.v:2.41-2.44" *)
  wire _14_;
  (* src = "demux_1to8_gen.v:2.41-2.44" *)
  wire _15_;
  (* src = "demux_1to8_gen.v:2.41-2.44" *)
  wire _16_;
  (* src = "demux_1to8_gen.v:2.41-2.44" *)
  wire _17_;
  (* src = "demux_1to8_gen.v:2.41-2.44" *)
  wire _18_;
  (* src = "demux_1to8_gen.v:2.41-2.44" *)
  wire _19_;
  (* src = "demux_1to8_gen.v:2.41-2.44" *)
  wire _20_;
  (* src = "demux_1to8_gen.v:2.41-2.44" *)
  wire _21_;
  (* src = "demux_1to8_gen.v:2.59-2.62" *)
  wire _22_;
  (* src = "demux_1to8_gen.v:2.59-2.62" *)
  wire _23_;
  (* src = "demux_1to8_gen.v:2.59-2.62" *)
  wire _24_;
  (* src = "demux_1to8_gen.v:2.72-2.73" *)
  input i;
  wire i;
  (* src = "demux_1to8_gen.v:3.9-3.10" *)
  wire [31:0] k;
  (* src = "demux_1to8_gen.v:2.41-2.44" *)
  output [7:0] out;
  wire [7:0] out;
  (* src = "demux_1to8_gen.v:2.59-2.62" *)
  input [2:0] sel;
  wire [2:0] sel;
  sky130_fd_sc_hd__and4_1 _25_ (
    .A(_24_),
    .B(_22_),
    .C(_23_),
    .D(_13_),
    .X(_21_)
  );
  sky130_fd_sc_hd__and4b_1 _26_ (
    .A_N(_22_),
    .B(_23_),
    .C(_13_),
    .D(_24_),
    .X(_20_)
  );
  sky130_fd_sc_hd__and4b_1 _27_ (
    .A_N(_23_),
    .B(_13_),
    .C(_24_),
    .D(_22_),
    .X(_19_)
  );
  sky130_fd_sc_hd__nor4bb_1 _28_ (
    .A(_22_),
    .B(_23_),
    .C_N(_13_),
    .D_N(_24_),
    .Y(_18_)
  );
  sky130_fd_sc_hd__and4b_1 _29_ (
    .A_N(_24_),
    .B(_22_),
    .C(_23_),
    .D(_13_),
    .X(_17_)
  );
  sky130_fd_sc_hd__nor4bb_1 _30_ (
    .A(_24_),
    .B(_22_),
    .C_N(_23_),
    .D_N(_13_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor4bb_1 _31_ (
    .A(_24_),
    .B(_23_),
    .C_N(_13_),
    .D_N(_22_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor4b_1 _32_ (
    .A(_24_),
    .B(_22_),
    .C(_23_),
    .D_N(_13_),
    .Y(_14_)
  );
  assign k = 32'd8;
  assign _24_ = sel[2];
  assign _22_ = sel[0];
  assign _23_ = sel[1];
  assign _13_ = i;
  assign out[7] = _21_;
  assign out[6] = _20_;
  assign out[5] = _19_;
  assign out[4] = _18_;
  assign out[3] = _17_;
  assign out[2] = _16_;
  assign out[1] = _15_;
  assign out[0] = _14_;
endmodule
